// Code generated by "stringer -type=monitoringCommand"; DO NOT EDIT.

package monitoring

import "strconv"

const _monitoringCommand_name = "cmdStartcmdKillcmdStop"

var _monitoringCommand_index = [...]uint8{0, 8, 15, 22}

func (i monitoringCommand) String() string {
	i -= 4
	if i < 0 || i >= monitoringCommand(len(_monitoringCommand_index)-1) {
		return "monitoringCommand(" + strconv.FormatInt(int64(i+4), 10) + ")"
	}
	return _monitoringCommand_name[_monitoringCommand_index[i]:_monitoringCommand_index[i+1]]
}
