// Code generated by "stringer -type=monitoringStage"; DO NOT EDIT.

package monitoring

import "strconv"

const _monitoringStage_name = "execStoppedexecStartingexecMonitoringexecFinish"

var _monitoringStage_index = [...]uint8{0, 11, 23, 37, 47}

func (i monitoringStage) String() string {
	if i < 0 || i >= monitoringStage(len(_monitoringStage_index)-1) {
		return "monitoringStage(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _monitoringStage_name[_monitoringStage_index[i]:_monitoringStage_index[i+1]]
}
